<a href="https://colab.research.google.com/github/manijenkins/ml/blob/develop/ML_GROUP038.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier 
import np_utils 
from sklearn.model_selection import cross_val_score 
from sklearn.model_selection import KFold 
from sklearn.preprocessing import LabelEncoder 
from sklearn.pipeline import Pipeline

In [0]:
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler 
import math
from tensorflow.keras.callbacks import LearningRateScheduler

In [0]:
from tensorflow.keras.optimizers import SGD

In [0]:
from google.colab import files
file = files.upload()

data=pd.read_csv("ionosphere_data.csv")

In [0]:
data.shape

(350, 35)

In [0]:
data.head(10)

1  0  0.99539  -0.05889  0.85243  ...  0.42267  -0.54487  0.18641  -0.45300  g
0  1  0  1.00000  -0.18829  0.93035  ... -0.16626  -0.06288 -0.13738  -0.02447  b
1  1  0  1.00000  -0.03365  1.00000  ...  0.60436  -0.24180  0.56045  -0.38238  g
2  1  0  1.00000  -0.45161  1.00000  ...  0.25682   1.00000 -0.32382   1.00000  b
3  1  0  1.00000  -0.02401  0.94140  ... -0.05707  -0.59573 -0.04608  -0.65697  g
4  1  0  0.02337  -0.00592 -0.09924  ...  0.00000   0.00000 -0.00039   0.12011  b
5  1  0  0.97588  -0.10602  0.94601  ... -0.04262  -0.81318 -0.13832  -0.80975  g
6  0  0  0.00000   0.00000  0.00000  ...  1.00000   1.00000  0.00000   0.00000  b
7  1  0  0.96355  -0.07198  1.00000  ...  0.45114  -0.72779  0.38895  -0.73420  g
8  1  0 -0.01864  -0.08459  0.00000  ...  0.16595   0.24086 -0.08208   0.38065  b
9  1  0  1.00000   0.06655  1.00000  ...  0.30996  -0.89093  0.22995  -0.89158  g

[10 rows x 35 columns]

In [0]:
X=data.iloc[:,:-1].values
X

array([[ 1.     ,  0.     ,  1.     , ..., -0.06288, -0.13738, -0.02447],
       [ 1.     ,  0.     ,  1.     , ..., -0.2418 ,  0.56045, -0.38238],
       [ 1.     ,  0.     ,  1.     , ...,  1.     , -0.32382,  1.     ],
       ...,
       [ 1.     ,  0.     ,  0.94701, ...,  0.00442,  0.92697, -0.00577],
       [ 1.     ,  0.     ,  0.90608, ..., -0.03757,  0.87403, -0.16243],
       [ 1.     ,  0.     ,  0.8471 , ..., -0.06678,  0.85764, -0.06151]])

In [0]:
y=data.iloc[:,-1].values
y

array(['b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b',
       'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g',
       'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b',
       'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g',
       'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b',
       'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g',
       'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b',
       'g', 'b', 'g', 'b', 'g', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b',
       'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g',
       'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b',
       'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g',
       'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b',
       'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g',
       'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g', 'b', 'g

In [0]:
X.shape

(350, 34)

In [0]:
seed=7
np.random.seed(seed)


In [0]:
encoder = LabelEncoder() 
encoder.fit(y) 
Y= encoder.transform(y)
Y

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [0]:
epochs = 50
def baseline_model(): 
    # create model 
    model = Sequential() 
    model.add(Dense(34, input_dim=34, activation= "relu" )) 
    model.add(Dense(16, activation= "relu" ))
    model.add(Dense(1, activation= "sigmoid" )) 
    # Compile model
     
    learning_rate = 0.1 
    decay_rate = learning_rate / epochs 
    momentum = 0.8 
    sgd = SGD(lr=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False)
    model.compile(loss= "binary_crossentropy" , optimizer=sgd, metrics=[ "accuracy" ]) 
    return model

In [0]:
estimator = KerasClassifier(build_fn=baseline_model, nb_epoch=epochs, batch_size=1, verbose=0)

In [0]:
# evaluate using 10-fold cross validation
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, Y, cv=kfold)
print(results.mean())

0.7410317599773407


In [0]:
estimators = [] 
estimators.append(( "standardize" , StandardScaler())) 
estimators.append(( "mlp" , KerasClassifier(build_fn=baseline_model, nb_epoch=epochs, batch_size=28, verbose=2))) 
pipeline = Pipeline(estimators) 
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed) 
results = cross_val_score(pipeline, X, Y, cv=kfold) 
print("Larger: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Train on 315 samples
315/315 - 1s - loss: 0.4838 - accuracy: 0.7968
36/1 - 0s - loss: 0.2020 - accuracy: 0.9444
Train on 316 samples
316/316 - 0s - loss: 0.5314 - accuracy: 0.7880
35/1 - 0s - loss: 0.4889 - accuracy: 0.8286
Train on 316 samples
316/316 - 1s - loss: 0.4826 - accuracy: 0.7816
35/1 - 0s - loss: 0.2344 - accuracy: 0.9429
Train on 316 samples
316/316 - 0s - loss: 0.6075 - accuracy: 0.7152
35/1 - 0s - loss: 0.3844 - accuracy: 0.8000
Train on 316 samples
316/316 - 0s - loss: 0.5267 - accuracy: 0.7184
35/1 - 0s - loss: 0.2175 - accuracy: 0.9143
Train on 316 samples
316/316 - 1s - loss: 0.5216 - accuracy: 0.7373
35/1 - 0s - loss: 0.2426 - accuracy: 0.8857
Train on 316 samples
316/316 - 0s - loss: 0.4439 - accuracy: 0.8133
35/1 - 0s - loss: 0.3060 - accuracy: 0.8571
Train on 316 samples
316/316 - 1s - loss: 0.5845 - accuracy: 0.7215
35/1 - 0s - loss: 0.3814 - accuracy: 0.8857
Train on 316 samples
316/316 - 0s - loss: 0.5238 - accuracy: 0.7911
35/1 - 0s - loss: 0.2900 - accuracy:

In [0]:
model = Sequential() 
model.add(Dense(34, input_dim=34, activation= "relu" )) 
model.add(Dense(16, activation= "relu" ))
model.add(Dense(1, activation= "sigmoid" )) 
# Compile model     
learning_rate = 0.1 
decay_rate = learning_rate / epochs 
momentum = 0.8 
sgd = SGD(lr=learning_rate, momentum=momentum, decay=decay_rate, nesterov=False)
model.compile(loss= "binary_crossentropy" , optimizer=sgd, metrics=[ "accuracy" ])
model.fit(X, Y, validation_split=0.33, nb_epoch=epochs, batch_size=28, verbose=2)

Train on 235 samples, validate on 116 samples
Epoch 1/50
235/235 - 3s - loss: 0.6253 - accuracy: 0.6468 - val_loss: 0.6501 - val_accuracy: 0.6121
Epoch 2/50
235/235 - 0s - loss: 0.4516 - accuracy: 0.8298 - val_loss: 0.4325 - val_accuracy: 0.8793
Epoch 3/50
235/235 - 0s - loss: 0.3222 - accuracy: 0.8766 - val_loss: 0.3541 - val_accuracy: 0.9138
Epoch 4/50
235/235 - 0s - loss: 0.2428 - accuracy: 0.9319 - val_loss: 0.0974 - val_accuracy: 0.9741
Epoch 5/50
235/235 - 0s - loss: 0.2062 - accuracy: 0.9319 - val_loss: 0.0877 - val_accuracy: 0.9828
Epoch 6/50
235/235 - 0s - loss: 0.1366 - accuracy: 0.9660 - val_loss: 0.1045 - val_accuracy: 0.9828
Epoch 7/50
235/235 - 0s - loss: 0.1168 - accuracy: 0.9617 - val_loss: 0.0597 - val_accuracy: 0.9828
Epoch 8/50
235/235 - 0s - loss: 0.1149 - accuracy: 0.9489 - val_loss: 0.0497 - val_accuracy: 0.9828
Epoch 9/50
235/235 - 0s - loss: 0.1293 - accuracy: 0.9660 - val_loss: 0.0595 - val_accuracy: 0.9828
Epoch 10/50
235/235 - 0s - loss: 0.1105 - accuracy: 0.

In [0]:
def step_decay(epoch): 
    initial_lrate = 0.1 
    drop = 0.5 
    epochs_drop = 5.0 
    lrate = initial_lrate * math.pow(drop, math.floor((1+epoch)/epochs_drop)) 
    return lrate

In [0]:
model = Sequential() 
model.add(Dense(34, input_dim=34, activation= "relu" ))
model.add(Dense(25, activation= "relu" ))
model.add(Dense(25, activation= "relu" ))
model.add(Dense(7, activation= "relu" ))
model.add(Dense(3, activation= "relu" ))
model.add(Dense(2, activation= "relu" ))

model.add(Dense(1, activation= "sigmoid" ))
sgd = SGD(lr=0.00, momentum=0.95, decay=0.0, nesterov=False) 
model.compile(loss= "binary_crossentropy" , optimizer=sgd, metrics=[ "accuracy" ])

In [0]:
# learning schedule callback 
lrate = LearningRateScheduler(step_decay) 
callbacks_list = [lrate] 
# Fit the model 
model.fit(X, Y, validation_split=0.33, nb_epoch=50, batch_size=1, callbacks=callbacks_list, verbose=2) 


Train on 235 samples, validate on 116 samples
Epoch 1/50
235/235 - 3s - loss: 0.7264 - accuracy: 0.6255 - val_loss: 0.4802 - val_accuracy: 0.9224
Epoch 2/50
235/235 - 0s - loss: 0.8969 - accuracy: 0.5064 - val_loss: 0.4008 - val_accuracy: 0.9224
Epoch 3/50
235/235 - 0s - loss: 0.9198 - accuracy: 0.4979 - val_loss: 0.4193 - val_accuracy: 0.9224
Epoch 4/50
235/235 - 0s - loss: 0.8380 - accuracy: 0.4766 - val_loss: 0.9236 - val_accuracy: 0.0776
Epoch 5/50
235/235 - 0s - loss: 0.8345 - accuracy: 0.5149 - val_loss: 1.3345 - val_accuracy: 0.0776
Epoch 6/50
235/235 - 0s - loss: 0.7528 - accuracy: 0.5149 - val_loss: 0.7844 - val_accuracy: 0.0776
Epoch 7/50
235/235 - 0s - loss: 0.7501 - accuracy: 0.5191 - val_loss: 0.4593 - val_accuracy: 0.9224
Epoch 8/50
235/235 - 0s - loss: 0.7587 - accuracy: 0.5106 - val_loss: 0.5049 - val_accuracy: 0.9224
Epoch 9/50
235/235 - 1s - loss: 0.7770 - accuracy: 0.5277 - val_loss: 0.3617 - val_accuracy: 0.9224
Epoch 10/50
235/235 - 0s - loss: 0.7170 - accuracy: 0.

In [0]:
Y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,